export const endpoints = {
	login: "/auth/login",
	verify: "/auth/verify",
	register: "/auth/register",
	qrConfirm: "/auth/qr_confirm",
	followChannels: "/home/follow_channel",
	liveChannelList: "/follow/channelListbyLive",
	tags: "/streams/tags",
	secondCategory: "/browse/second_category",
	homeCategory: "/streams/get_categories",
	updateStreamInfo: "/streams/update_streaminfo",
	getStreamInfo: "/streams/get_streaminfo",
	updateStreamKey: "/streams/update_streamkey",
	vodSetting: "/streams/update_vodshowpast",
	videoSlider: "/streams/get_streamsliderlimit",
	startLive: "/profile/go_live",
	updateProfile: "/profile/update_profile",
	vodByCategoryID: "/browse/VODByCategoryID",
	channelData: "/profile/channeldataBychannelID",
	homeLive: "/streams/get_streams",
	profileData: "/profile/channeldataByuserID",
	follow: "/follow/addfollow",
	// Add more endpoints as needed
};
